%%{
    init: {
        "theme":"base",
        "themeVariables": {
            'labelBoxBorderColor': '#ff0000'
        },
        "sequence": { 
            "wrap": true, 
            "width": 200 
        } 
    }
}%%
sequenceDiagram
    participant Client
    participant Sec as Security
    participant Router as DebtRouter
    box orange Controller
        participant BaseCont as BaseController
        participant Cont as DebtModelController extends BaseController
    end
    participant PGClient as PostgreSQLClient
    participant BaseModel as BaseModel 
    participant Model as DebtModelModel extends BaseModel
    participant DB as [(Database)]

    Client->>+Router: GET /debts/:debtName (ReadOne debt)
    Note over Sec, Router: this method defined in UserManagement/read.mmd
    Router->>+Sec: verifyToken(req)
    alt Token decode error | Token expired | Invalid token
        Sec-->>Router: next(new UnauthorizedError('Invalid credentials'))
        Router-->>Client: 🔴401, "Could not validate credentials"
    end
    Sec-->>-Router: decoded user object 

    Note over Sec, Router: this method defined in UserManagement/create.mmd
    Router->>Router: MethodValidator(allowedMethods)
    opt path not available
        Router-->>Client: 🔴404, "<path> not available"
    end
    opt method not allowed
        Router-->>Client: 🔴405, "<method> not allowed for <path>"
    end
    Router->>+Cont: getOneDebt(req, res, next)
    Cont->>Cont: Destructoring parameters
    
    Note over Cont, BaseCont: requiredFields = ['debtName']
    Cont->>+BaseCont: verifyField({debtName}, requiredFields)
    Note over BaseCont: also type conversion eg. string -> decimal
    opt missing required fields
        BaseCont-->>Cont: throw Error('<field> is required')
        Cont-->>Router: next(BadRequestError(error))
        Router-->>Client: 🔴400, "<field> is required"
    end
    BaseCont-->>-Cont: return true
    
    Note over Cont, BaseCont: this method defined in UserManagement/read.mmd
    Cont->>+BaseCont: getCurrentUser(req)
    BaseCont-->>-Cont: User data
    opt user not found
        Cont-->>Router: throw NotFoundError('User not found')
        Router-->>Client: 🔴404, "User not found"
    end

    Cont->>+Model: findOne([debtName, userEmail])
    Model->>+BaseModel: pass call
    Note over BaseModel: this method defined in BankAccountManagement/create.mmd
    BaseModel->>BaseModel: validateSchema(data) 
    Note over BaseModel: also validate each input individually by Regex: as each type of input has its own pattern, specific requirements and constraints.
    opt missing required field || invalid type || RegEx does not match
        BaseModel-->>Model: throw new Error('<field> is invalid')
        Model-->>Cont: throw error
        Cont-->>Router: next(new BadRequestError(error.message))
        Router-->>Client: 🔴400, "<error.message>"
    end
    Note over BaseModel: query with prepare Statements
    BaseModel->>BaseModel: query(sql, params)
    BaseModel->>+DB: do operation
    DB-->>-BaseModel: result
    opt any error occurred
        BaseModel-->>Model: throw Error
        Model-->>Cont: pass error
        Cont-->>Router: next(error)
        Router-->>Client: 🔴500, "something went wrong"
    end
    BaseModel-->>-Model: return debt object
    Model-->>-Cont: pass result
    opt debt not found
        Cont-->>Router: throw NotFoundError('debt not found')
        Router-->>Client: 🔴404, "debt not found"
    end

    Cont->>+BaseCont: verifyOwnership(user, [debt])
    opt debt's user email does not match current user email
        BaseCont-->>Cont: return false
        Cont-->>Router: throw ForbiddenError('You are not allowed to access this resource')
        Router-->>Client: 🔴403, "You are not allowed to access this resource"
    end
    BaseCont-->>-Cont: return true
    Cont->>Cont: formatResponse(200, '"debt retrieved successfully"', { debt })
    Cont-->>-Router: Formatted response
    Router-->>-Client: 🟢200, { status: 200, message: "debt retrieved successfully", data: { debt } }