sequenceDiagram
    autonumber
<<<<<<<< HEAD:design/BaseController.mmd
    title General Request Handling Flow
========
    title Middleware flow
>>>>>>>> 061f7b7138297caa13f9dcc61f189ae6c2c0e5fa:design/Middleware.mmd
    Actor Client
    participant Router
    participant BaseController
    participant UserModel
    participant TargetModel
    participant Database

    %% alt เลือกทำอย่างใดอย่างหนึ่ง
    %% opt จะทำหรือไม่ทำก็ได้
    Note over Client,Router: with body {JWT token, ...}
    Client->>Router: HTTP Request
    rect rgb(185,185,185)
    Note over Client, Database: these processes are Middleware that process before any tasks
        opt verify method
            Router->>Router: verify method
            rect rgb(239, 157, 157)
            Note right of Client: method not allowed
                Note over Router,Client: JSON Response: {status_code, message, data(if any)}
                Router-->>Client: 405 Method Not Allowed
            end
        end
        Router->>BaseController: call specific method (e.g., createBankAccount)
        rect rgb(191, 223, 255)
        Note right of Client: verify request body
            BaseController->>BaseController: verifying if a Cookies token was attached with request in the body?<br>isCookie(token: str)
            
            opt Cookie not found
                BaseController-->>Router: throw error missing token in the body
                Note over Router,Client: JSON Response: {status_code, message, data(if any)}
                Router-->>Client: 400 insufficient arguments
            end
            Note over BaseController: successful, do nothing. and goto next verification
        end
        rect rgb(238, 203, 157)
        Note right of Client: authorization
            Note over BaseController, UserModel: verify_client(token)<br/>to check if client was a user or not
            BaseController->>UserModel: verify_client(token)
            UserModel->>UserModel: this.decode_token(token)
            UserModel->>UserModel: this.get_user_by_id(userId)
            UserModel->>Database: Perform database operation
            opt not found
                Database-->>UserModel: return empty object
                UserModel-->>BaseController: return false
                BaseController-->>Router: throw Client unauthorized
                Note over Router,Client: JSON Response: {status_code, message, data(if any)}
                Router-->>Client: 401 Unauthorized
            end
            Database->>UserModel: return user object
            UserModel->>BaseController: return true
            Note over UserModel, BaseController: and goto next verification
        end
        rect rgb(192, 157, 239)
        Note right of Client: Forbidden
            Note over BaseController, UserModel: right_verify(currentUser)<br/>to check if a user was allowed to do a RUD operation to TargetModel<br/>e.g., to modify/read data, you need to be an owner
            BaseController->>TargetModel: right_verify(currentUser)
            TargetModel->>TargetModel: TargetModel.get_owner_by_id(objectId)
            alt successful
                TargetModel->>BaseController: return true
            else User doesn't have right to access/modify
                TargetModel-->>BaseController: return false
                BaseController-->>Router: Indicate forbidden access
                Note over Router,Client: JSON Response: {status_code, message, data(if any)}
                Router-->>Client: 403 Forbidden
            end
        end
    end
    rect rgb(157, 239, 190)
    Note right of Client: Successful Operation
        BaseController->>TargetModel: perform CRUD operation (e.g., create, read, update, delete)
        Note over TargetModel: TRY Block
        Note over TargetModel: CRUD Operation design individually for each entity
        alt Create
            TargetModel->>TargetModel: verify data is not null
            TargetModel->>Database: Perform database operation
            Database->>TargetModel: operation successful 
            TargetModel->>BaseController: RESULT: str = object created Id
        else Read one
            TargetModel->>TargetModel: verify id is not null
            Note over TargetModel: function general_query_function(findOneorMany, query, sort)<br/>query: object<br/>sort: enum(asc, desc)
            TargetModel->>TargetModel: general_query_function(One, query, sort)
            TargetModel->>Database: Perform database operation
            Database->>TargetModel: operation successful
            TargetModel->>BaseController: RESULT: obj = read data object {...}
        else Read all
            TargetModel->>TargetModel: general_query_function(Many, query, sort)
            TargetModel->>Database: Perform database operation
            Database->>TargetModel: operation successful
            TargetModel->>BaseController: RESULT: arr = read array of object data [{...}, {...}, {...}, ...]
        else Update
            TargetModel->>TargetModel: verify id, dataToUpdate is not null 

            Note over TargetModel:get an updating document to include the empty field<br/>in the incoming updating data object
            TargetModel->>TargetModel: general_query_function(One, id, None)
            TargetModel->>Database: Perform database operation
            Database->>TargetModel: operation successful

            TargetModel->>TargetModel: include data into incoming updated data 

            Note over TargetModel: do an updating operation
            TargetModel->>TargetModel: update_one(id)
            TargetModel->>Database: Perform database operation
            Database->>TargetModel: operation successful

            Note over TargetModel: get the updated document
            TargetModel->>TargetModel: general_query_function(One, id, None)
            TargetModel->>Database: Perform database operation
            Database->>TargetModel: operation successful

            TargetModel->>BaseController: RESULT: obj = updated object {...}
        else delete
            TargetModel->>TargetModel: verify id is not null
            Note over TargetModel: do a deleting operation
            TargetModel->>TargetModel: delete_one(id)
            TargetModel->>Database: Perform database operation
            Database->>TargetModel: operation successful
            TargetModel->>BaseController: RESULT: bool = true
        end
        
        BaseController->>Router: return message("<action> success") and data(if any) from model
        Note over Router,Client: JSON Response: {status_code, message, data(if any)}
        Router->>Client: 200 OK with JSON response
    end
    Note over BaseController: CATCH Block
    rect rgb(255, 255, 153)
    Note right of Client: TargetModel Operation Failed
    opt Operation Failed
        Database-->>TargetModel: Operation fails
        TargetModel-->>BaseController: throw the error message.
        BaseController-->>Router: Pass error information
        Note over Router,Client: JSON Response: {status_code, message, data(if any)}
        Router-->>Client: Appropriate error code (e.g. 500, Internal Server Error)
    end
    end
