@startuml  Use case diagram
left to right direction
actor User as user

rectangle "System"{
rectangle "Authentication" {
  usecase "Authentication" as auth
  usecase "Login by Username and Password" as login
  usecase "Login by Google account" as google
  usecase "Login by Apple account" as apple
}

rectangle "User Datas" {
  usecase "CRUD" as crud
  
  rectangle "Data Management" {
    usecase "Users" as users
    usecase "UserTransactions" as userTrans
    usecase "BankAccounts" as banks
    usecase "BankAccountTransactions" as bankTrans
    usecase "Debts" as debts
    usecase "DebtPayments" as debtPay
    usecase "Income-Expenses" as ies
  }
  
  usecase "Notifications" as noti
  usecase "Settings" as settings
}
usecase "Extract slip data" as extData
}

actor EasySlip as easy

user --> auth
login .left.> auth : include
google .left.> auth : include
apple .left.> auth : include

user --> crud
crud <.. users : include
crud <.. userTrans : include
crud <.. banks : include
crud <.. bankTrans : include
crud <.. debts : include
crud <.. debtPay : include
crud <.. ies : include
crud <.. noti : include
crud <.. settings : include

user --> extData
extData --> easy

@enduml