# Use an official Node.js runtime as the base image
FROM node:20-alpine

# Define the arguments
ARG APP_DOMAIN
ARG APP_PORT
ARG NODE_ENV

# Install curl for healthcheck
RUN apk add --no-cache curl

# Set the working directory
WORKDIR /usr/src/${APP_DOMAIN}

# Copy the package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY ./.src ./.src
COPY ./statics ./statics
COPY ./sql ./sql

# Expose the port from env
EXPOSE ${APP_PORT}

# Default command for starting the app
CMD if [ "$NODE_ENV" = "production" ]; then \
    npm run start; \
    elif [ "$NODE_ENV" = "test" ]; then \
    npm run test; \
    else \
    npm run dev; \
    fi
