# Use an official Node.js runtime as the base image
FROM node:20-alpine

# Define the arguments
ARG APP_DOMAIN
ARG NODE_ENV
ARG APP_PORT

# Install curl for healthcheck only
RUN apk update && apk add --no-cache curl

# Set the working directory
WORKDIR /usr/src/${APP_DOMAIN}

# Copy the package.json and package-lock.json
COPY package*.json ./

# Create logs directory
RUN mkdir -p /usr/src/${APP_DOMAIN}/logs

# # Set permissions
# RUN chown -R node:node /usr/src/${APP_DOMAIN}/logs

# # Switch to non-root user
# USER node

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY ./sql ./sql
COPY ./statics ./statics

COPY ./.src ./.src

# Expose the port from env
EXPOSE ${APP_PORT}

# Default command for starting the app (will be overridden by docker-compose if needed)
CMD ["npm", "run", "dev"]
