# Use an official Node.js runtime as the base image
FROM node:20-alpine

# Install curl for healthcheck
RUN apk add --no-cache curl

# Set the working directory
WORKDIR /usr/src/WealthTrack

# Copy the package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY ./.src ./.src

COPY ./statics ./statics

COPY ./sql ./sql

# Expose the port the app runs on
EXPOSE 3000

# Default command for starting the app
CMD ["npm", "run", "dev"]
