###
POST http://localhost:3000/api/v0.2/users
Content-Type: application/json
###
POST http://localhost:3000/api/v0.2/users
Content-Type: application/json

{
    "national_id": "123456789012",
    "username":"SaWatKiA",
    "email":"SaWAt.KiA@2000GMail.Com",
    "password":"1234567890",
    "confirm_password":"1234567890"
}
###
POST http://localhost:3000/api/v0.2/users
Content-Type: application/json

{
    "national_id": "123456789012343",
    "username":"SaWatKiA",
    "email":"SaWAt.KiA@2000GMail.Com",
    "password":"1234567890",
    "confirm_password":"1234567890"
}
###
POST http://localhost:3000/api/v0.2/users
Content-Type: application/json

{
    "national_id": "1234567890124",
    "username":"SaWatKiA",
    "email":"SaWAt.KiA@2000GMail.Com",
    "password":"1234567890",
    "confirm_password":"1234567890"
}
###
POST http://localhost:3000/api/v0.2/users/pw
Content-Type: application/json

{
    "email": "SaWAt.KiA@2000GMail.Com",
    "password": "1234567890",
}