sequenceDiagram
    title Bank Accounts
    participant Client
    participant Router
    participant Controller
    participant Bank as BankAccounk

    alt create a new bank account
        rect rgb(73,204,144)
            Client->>Router: POST /bank/create
        end
    else read a bank account
        rect rgb(142,172,252)
            Client->>Router: POST /bank/id
        end
    else read all bank aacounts
        rect rgb(152, 142, 232)
            Client->>Router: POST /bank/all
        end
    else update bank aacount
        rect rgb(252,182,142)
            Client->>Router: PUT  /bank/update
        end
    else delete bank account
        rect rgb(247,155,155)
            Client->>Router: DELETE /bank/delete
        end
    end