sequenceDiagram
    title Asset 
    participant Client
    participant Router
    participant Controller
    participant Asset as Asset

    alt create a new Asset account
        rect rgb(73,204,144)
            Client->>Router: POST /Asset/create
        end
    else read a Asset account
        rect rgb(142,172,252)
            Client->>Router: POST /Asset/id
        end
    else read all Asset aacounts
        rect rgb(152, 142, 232)
            Client->>Router: POST /Asset/all
        end
    else update Asset aacount
        rect rgb(252,182,142)
            Client->>Router: PUT  /Asset/update
        end
    else delete Asset account
        rect rgb(247,155,155)
            Client->>Router: DELETE /Asset/delete
        end
    end