sequenceDiagram
    title IncomeExpense 
    participant Client
    participant Router
    participant Controller
    participant InEx as IncomeExpense

    alt create a new IncomeExpense
        rect rgb(73,204,144)
            Client->>Router: POST /userTransaction/create
        end
    else read a IncomeExpense
        rect rgb(142,172,252)
            Client->>Router: POST /userTransaction/id
        end
    else read all IncomeExpenses
        rect rgb(152, 142, 232)
            Client->>Router: POST /userTransaction/all
        end
    else update IncomeExpense
        rect rgb(252,182,142)
            Client->>Router: PUT  /userTransaction/update
        end
    else delete IncomeExpense
        rect rgb(247,155,155)
            Client->>Router: DELETE /userTransaction/delete
        end
    end